### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ghost** [chsu7793/prj-rev-bwfs-tea-cozy#3]
Grade: Meets expectations

Nice work! You have good indentation and syntax. Add comments and alt attributes. As a next step, consider adding additional pages, videos, and images to your site. You can even add a drop down menu. I think you're ready for it!

**Comment by chsu7793** [comment]
thanks for the feedback! yes, i should definitely make comments throughout as a way to keep my codes more organized.
